# Generated by Django 5.0.4 on 2025-06-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShiftConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opening_time", models.TimeField(verbose_name="営業開始時間")),
                ("closing_time", models.TimeField(verbose_name="営業終了時間")),
                (
                    "idle_start",
                    models.TimeField(blank=True, null=True, verbose_name="アイドルタイム開始"),
                ),
                (
                    "idle_end",
                    models.TimeField(blank=True, null=True, verbose_name="アイドルタイム終了"),
                ),
                (
                    "min_staff",
                    models.PositiveIntegerField(default=1, verbose_name="最小必要人数"),
                ),
                (
                    "max_staff",
                    models.PositiveIntegerField(default=5, verbose_name="最大同時人数"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
