# Generated by Django 5.0.4 on 2025-06-10 01:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shiftConfig", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shiftconfiguration",
            name="max_staff",
        ),
        migrations.RemoveField(
            model_name="shiftconfiguration",
            name="min_staff",
        ),
        migrations.AddField(
            model_name="shiftconfiguration",
            name="break_after_6h",
            field=models.DurationField(
                default=datetime.timedelta(seconds=2700),
                editable=False,
                verbose_name="6時間超勤務時の休憩",
            ),
        ),
        migrations.AddField(
            model_name="shiftconfiguration",
            name="break_after_8h",
            field=models.DurationField(
                default=datetime.timedelta(seconds=3600),
                editable=False,
                verbose_name="8時間超勤務時の休憩",
            ),
        ),
        migrations.AddField(
            model_name="shiftconfiguration",
            name="closed_days",
            field=models.JSONField(
                blank=True, default=list, verbose_name="定休日（例：['月', '火']）"
            ),
        ),
        migrations.AddField(
            model_name="shiftconfiguration",
            name="shift_unit",
            field=models.PositiveIntegerField(
                choices=[(30, "30分単位"), (60, "60分単位")],
                default=30,
                verbose_name="シフト時間の最小単位",
            ),
        ),
        migrations.AddField(
            model_name="shiftconfiguration",
            name="weekday_max_staff",
            field=models.PositiveIntegerField(default=5, verbose_name="平日：最大同時人数"),
        ),
        migrations.AddField(
            model_name="shiftconfiguration",
            name="weekday_min_staff",
            field=models.PositiveIntegerField(default=1, verbose_name="平日：最小必要人数"),
        ),
        migrations.AddField(
            model_name="shiftconfiguration",
            name="weekend_max_staff",
            field=models.PositiveIntegerField(default=5, verbose_name="休日：最大同時人数"),
        ),
        migrations.AddField(
            model_name="shiftconfiguration",
            name="weekend_min_staff",
            field=models.PositiveIntegerField(default=1, verbose_name="休日：最小必要人数"),
        ),
    ]
