# Generated by Django 5.0.4 on 2025-06-11 01:51

import shiftConfig.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shiftConfig", "0002_remove_shiftconfiguration_max_staff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shiftconfiguration",
            name="id",
            field=models.PositiveIntegerField(
                default=shiftConfig.models.singleton_instance,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
