# Generated by Django 5.0.4 on 2025-04-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lineShift", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_user_id", models.CharField(max_length=50)),
                ("weekday", models.CharField(max_length=10)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("unavailable", models.BooleanField(default=False)),
            ],
        ),
    ]
