# Generated by Django 5.0.4 on 2025-04-24 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lineShift", "0002_shift"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shift",
            name="line_user_id",
            field=models.CharField(max_length=255),
        ),
    ]
