# Generated by Django 5.0.4 on 2025-04-24 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lineShift", "0003_alter_shift_line_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shift",
            old_name="weekday",
            new_name="day_of_week",
        ),
    ]
