# Generated by Django 5.0.4 on 2025-04-25 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lineShift", "0004_rename_weekday_shift_day_of_week"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shift",
            name="line_user_id",
        ),
        migrations.AddField(
            model_name="shift",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="lineShift.customuser",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customuser",
            name="line_user_id",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
