# Generated by Django 5.0.4 on 2025-04-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lineShift", "0005_remove_shift_line_user_id_shift_user_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="shiftsubmission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="shiftsubmission",
            name="user",
        ),
        migrations.AlterField(
            model_name="shift",
            name="day_of_week",
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name="DefaultShiftPreference",
        ),
        migrations.DeleteModel(
            name="ShiftSubmission",
        ),
    ]
