# Generated by Django 5.0.4 on 2025-04-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lineShift", "0006_alter_shiftsubmission_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shift",
            name="user",
        ),
        migrations.AddField(
            model_name="shift",
            name="line_user_id",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="shift",
            name="day_of_week",
            field=models.CharField(max_length=10),
        ),
    ]
