# Generated by Django 5.0.4 on 2025-04-30 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lineShift", "0007_remove_shift_user_shift_line_user_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shift",
            name="day_of_week",
        ),
        migrations.RemoveField(
            model_name="shift",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="shift",
            name="start_time",
        ),
        migrations.RemoveField(
            model_name="shift",
            name="unavailable",
        ),
        migrations.AddField(
            model_name="shift",
            name="shift_data",
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="shift",
            name="line_user_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
