# Generated by Django 5.2.1 on 2025-05-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lineShift", "0008_remove_shift_day_of_week_remove_shift_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
