# Generated by Django 5.2.1 on 2025-05-20 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lineShift", "0009_shift_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Shift",
            new_name="ContractShift",
        ),
    ]
