# Generated by Django 5.2.1 on 2025-05-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lineShift", "0010_rename_shift_contractshift"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_user_id", models.CharField(max_length=255)),
                ("week_start_date", models.DateField()),
                ("shift_data", models.JSONField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("line_user_id", "week_start_date")},
            },
        ),
    ]
